ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".prashum.online
REDIS_HOST: redis-"{{ env }}".prashum.online
CATALOGUE_HOST: catalogue-"{{ env }}".prashum.online
MYSQL_HOST: mysql-"{{ env }}".prashum.online
CART_HOST: cart-"{{ env }}".prashum.online
USER_HOST: user-"{{ env }}".prashum.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".prashum.online
SHIPPING_HOST: shipping-"{{ env }}".prashum.online
PAYMENT_HOST: payment-"{{ env }}".prashum.online
app_version: v3